openapi: 3.0.3
info:
  title: Patients API
  version: 0.0.1
  description: Patients API
servers:
  - url: 'https://metoonhathung-patient-service.herokuapp.com'
paths:
  /patients:
    get:
      summary: Get patients
      description: Get patients
      operationId: getPatients
      tags:
        - 'patients'
      parameters:
        - in: query
          name: patientsGetRequest
          required: false
          schema:
            $ref: '#/components/schemas/PatientsGetRequest'
        - in: query
          name: pagination
          required: false
          schema:
            $ref: '#/components/schemas/Pagination'
      responses:
        '200':
          description: Get all success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PatientsGetResponse'
    post:
      summary: Post patient
      description: Post patient
      operationId: postPatient
      tags:
        - 'patients'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatientPostRequest'
      responses:
        '200':
          description: Post success
  /patients/{id}:
    get:
      summary: Get patient
      description: Get patient
      operationId: getPatient
      tags:
        - 'patients'
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Get success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PatientGetResponse'
    put:
      summary: Put patient
      description: Put patient
      operationId: putPatient
      tags:
        - 'patients'
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatientPutRequest'
      responses:
        '200':
          description: Put success
    delete:
      summary: Delete patient
      description: Delete patient
      operationId: deletePatient
      tags:
        - 'patients'
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Delete success
components:
  schemas:
    Pagination:
      type: object
      properties:
        page:
          type: integer
          default: 1
        size:
          type: integer
          default: 10
        orderBy:
          type: string
          default: 'id'
        direction:
          type: string
          default: 'ASC'
    MetaResponse:
      type: object
      properties:
        total:
          type: integer
          format: int64
    PatientsGetRequest:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        gender:
          type: string
        age:
          type: integer
        email:
          type: string
        phoneNumber:
          type: string
    PatientPostRequest:
      type: object
      properties:
        name:
          type: string
        gender:
          type: string
        age:
          type: integer
        email:
          type: string
        phoneNumber:
          type: string
      required:
        - name
        - gender
        - age
        - phoneNumber
    PatientPutRequest:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        gender:
          type: string
        age:
          type: integer
        email:
          type: string
        phoneNumber:
          type: string
      required:
        - id
        - name
        - gender
        - age
        - phoneNumber
    PatientGetResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        gender:
          type: string
        age:
          type: integer
        email:
          type: string
        phoneNumber:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
    PatientsGetResponse:
      type: object
      properties:
        meta:
          $ref: '#/components/schemas/MetaResponse'
        data:
          type: array
          items:
            $ref: '#/components/schemas/PatientGetResponse'
