CREATE TABLE PATIENT (
    PATIENT_ID BIGSERIAL PRIMARY KEY NOT NULL,
    NAME VARCHAR (255) NOT NULL,
    GENDER VARCHAR (50) NOT NULL,
    AGE INT NOT NULL,
    EMAIL VARCHAR (50),
    PHONE_NUMBER VARCHAR (50) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);